### ISSUE TITLE
Possible incompatibility with mod Cubic Chunks

### ISSUE THREAD

**Issue by steampunko** [DimensionalDevelopment/VanillaFix#106]
I have tried running a server with Cubic Chunks while joining using this mod, but when I do I see the world and then immediately get booted out of the server with the mod stating the game crashed. This has never happened until I installed vanillafix... 
[crash.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/2279941/crash.txt)

**Comment by temp1011** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: 4
    at net.optifine.util.RenderChunkUtils.getCountBlocks(RenderChunkUtils.java:25)
    at net.optifine.util.RenderChunkUtils.getRelativeBufferSize(RenderChunkUtils.java:37)
    ...
```
seems like optifine to me

**Comment by steampunko** [comment]
It works fine without VanillaFix, and VanillaFix works with Optifine
(without Cubic Chunks installed).
