### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/VanillaFix#119]
Why is this showing a Vanilla fix issue when updating to the new version of forge but I dont have sponge in my pack.

[16:56:39] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[16:56:39] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.teamwizardry.librarianlib.asm.LibLibTransformer' was detected and will no longer process meta class data
[16:56:39] [main/INFO] [STDOUT]: [elucent.elulib.asm.ASMTransformer:patchRenderItemASM:124]: Successfully loaded RenderItem ASM!
[16:56:39] [main/INFO] [EnderCore ASM]: Transforming Class [net.minecraft.client.renderer.RenderItem], Method [func_180453_a, func_184391_a]
[16:56:39] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.client.renderer.RenderItem Finished.
[16:56:39] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:client.MixinMalisisRenderer$MixinBlockModelShapes, name: net.malisis.core.asm.mixin.core.client.MixinMalisisRenderer$MixinBlockModelShapes
[16:56:39] [main/INFO] [STDOUT]: [com.teamwizardry.wizardry.asm.WizardryTransformer:log:28]: [wizardry ASM] Successfully patched -> 'func_70091_d', 'move' with '(Lnet/minecraft/entity/MoverType;DDD)V'
[16:56:39] [main/FATAL] [mixin]: Mixin prepare failed preparing client.MixinMinecraft in mixins.vanillafix.bugs.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [JustEnoughIDs-1.0.2-25.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) [?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:56:39] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.vanillafix.bugs.json:client.MixinMinecraft] from phase [DEFAULT] in config [mixins.vanillafix.bugs.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
[16:56:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:56:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:56:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:56:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:56:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[16:56:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:56:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ZombieHDGaming** [comment]
Because we use Mixins which is made by Sponge........not everything is used by Sponge, it's just a library they host. As for the issue, I'll need to investigate into it, but it might be a mod compat issue with another mod.

**Comment by TacticalUniverse** [comment]
I figured it out Its Just Enough IDs causing the crash

**Comment by ZombieHDGaming** [comment]
No, it is not at all causing the crash.
