### ISSUE TITLE
Crash on startup with VanillaFix-1.1-130

### ISSUE THREAD

**Issue by MJRamon** [DimensionalDevelopment/VanillaFix#144]
```
[03:04:01] [main/INFO] [org.dimdev.vanillafix.dynamicresources.DynamicTextureMap]: Created 32x32 'textures' atlas
[03:04:01] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.TextureStitchEvent$Pre@4bc0d64a:
java.lang.RuntimeException: java.lang.NullPointerException
	at codechicken.lib.reflect.ReflectionManager.getField(ReflectionManager.java:237) ~[ReflectionManager.class:?]
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.grabLoader(CCBlockStateLoader.java:242) ~[CCBlockStateLoader.class:?]
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.onTextureStitchPre(CCBlockStateLoader.java:124) ~[CCBlockStateLoader.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_779_CCBlockStateLoader_onTextureStitchPre_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:196) [ForgeHooksClient.class:?]
	at org.dimdev.vanillafix.dynamicresources.DynamicTextureMap.init(DynamicTextureMap.java:63) [DynamicTextureMap.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:572) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:512) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3930) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Field.get(Unknown Source) ~[?:1.8.0_191]
	at codechicken.lib.reflect.ReflectionManager.getField(ReflectionManager.java:235) ~[ReflectionManager.class:?]
	... 26 more
[03:04:01] [main/ERROR] [FML]: Index: 2 Listeners:
[03:04:01] [main/ERROR] [FML]: 0: HIGHEST
[03:04:01] [main/ERROR] [FML]: 1: ASM: mods.betterfoliage.client.texture.LeafRegistry@6e7e0fd2 handlePreStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 2: ASM: codechicken.lib.model.loader.blockstate.CCBlockStateLoader@4174d996 onTextureStitchPre(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 3: NORMAL
[03:04:01] [main/ERROR] [FML]: 4: ASM: class com.direwolf20.buildinggadgets.ClientProxy registerSprites(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 5: ASM: net.blay09.mods.cookingforblockheads.client.ClientProxy@41fe4a6c registerIcons(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 6: ASM: blusunrize.immersiveengineering.client.ClientProxy@6e52f0ac textureStichPre(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 7: ASM: antibluequirk.alternatingflux.client.ClientProxy@7d087977 registerTextures(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 8: ASM: cofh.core.proxy.EventHandlerClient@6ed35da9 handleTextureStitchPreEvent(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 9: ASM: mods.betterfoliage.client.render.RenderGrass@5cfc428c onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 10: ASM: mods.betterfoliage.client.render.RenderMycelium@72249fe6 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 11: ASM: mods.betterfoliage.client.render.RenderLeaves@497d4701 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 12: ASM: mods.betterfoliage.client.render.RenderCactus@36d2acfa onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 13: ASM: mods.betterfoliage.client.render.RenderLilypad@368ccc52 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 14: ASM: mods.betterfoliage.client.render.RenderReeds@5ab7ea26 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 15: ASM: mods.betterfoliage.client.render.RenderAlgae@247fff57 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 16: ASM: mods.betterfoliage.client.render.RenderCoral@3cf4a3d4 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 17: ASM: mods.betterfoliage.client.render.RenderLog@7547fa66 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 18: ASM: mods.betterfoliage.client.render.RenderNetherrack@ac29f1a onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 19: ASM: mods.betterfoliage.client.render.RenderConnectedGrass@b23b59c onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 20: ASM: mods.betterfoliage.client.render.RenderConnectedGrassLog@5e0871f4 onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 21: ASM: mods.betterfoliage.client.render.RisingSoulTextures@416284fb onStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 22: ASM: com.jaquadro.minecraft.chameleon.core.ClientProxy@6bd2c17f onPreTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 23: ASM: codechicken.lib.texture.TextureUtils@4b85ec07 textureLoad(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 24: ASM: com.denbukki.curio.client.TextureStichHandler@22feb85e onTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 25: ASM: class com.ferreusveritas.dynamictrees.event.TextureGenerationHandler onTextureStitchEvent(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 26: ASM: com.mrcrayfish.furniture.handler.ClientEvents@365224f9 onTextureStitchPre(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 27: ASM: net.malisis.core.registry.ClientRegistry@1f989aec onTextureStitchEvent(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 28: ASM: mob_grinding_utils.events.ParticleTextureStitchEvent@ce3f5ee onTextureStitchPre(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 29: ASM: openblocks.client.renderer.item.stencil.StencilTextureManager@245ddb57 onTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 30: ASM: openblocks.client.renderer.block.canvas.CanvasTextureManager@2cc9d026 onTextureStitchEvent(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 31: ASM: openblocks.client.renderer.TextureUploader@6e3f9c3b onTextureStitchEvent(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 32: ASM: openblocks.client.ClientProxy$FluidTextureRegisterListener@27d72d6e onTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 33: ASM: me.ferdz.placeableitems.event.TextureStichHandler@5b7910ab onTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 34: ASM: thebetweenlands.client.handler.TextureStitchHandler@391dd86e onTextureStitchPre(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 35: ASM: epicsquid.mysticallib.LibEvents@abae67c onTextureStitchPre(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 36: ASM: team.chisel.client.TextureStitcher@ef98e6e onTextureStitchPre(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 37: ASM: openblocks.client.SoundIconRegistry@373d009c registerIcons(Lnet/minecraftforge/client/event/TextureStitchEvent;)V
[03:04:01] [main/ERROR] [FML]: 38: ASM: epicsquid.mysticallib.LibRegistry@7eead173 onTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent;)V
[03:04:01] [main/ERROR] [FML]: 39: ASM: epicsquid.mysticallib.LibEvents@abae67c onTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent;)V
[03:04:01] [main/ERROR] [FML]: 40: LOW
[03:04:01] [main/ERROR] [FML]: 41: ASM: mods.betterfoliage.client.render.RenderCactus$cactusTextures$1@55c79732 handlePreStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 42: ASM: mods.betterfoliage.client.texture.StandardLeafSupport@5ab4d0be handlePreStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 43: ASM: mods.betterfoliage.client.texture.StandardGrassSupport@1e9ad24a handlePreStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 44: ASM: mods.betterfoliage.client.render.StandardLogSupport@570a28f handlePreStitch(Lnet/minecraftforge/client/event/TextureStitchEvent$Pre;)V
[03:04:01] [main/ERROR] [FML]: 45: LOWEST
[03:04:01] [main/ERROR] [FML]: 46: ASM: class com.infinityraider.agricraft.handler.TextureStitchHandler onTextureStitch(Lnet/minecraftforge/client/event/TextureStitchEvent;)V
[03:04:01] [main/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_779_CCBlockStateLoader_onTextureStitchPre_Pre (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_779_CCBlockStateLoader_onTextureStitchPre_Pre)
```

**Comment by yourmum21** [comment]
I encountered the same error in version 1.0.10-150 of VanillaFix (and malisiscore1.12.2-6.5.1, malisisdoors-1.12.2-7.3.0) HOWEVER did i test it with version VanillaFix-1.0.10-99 which is the 2. newest version at this moment, which launched the game properly.

Hope this helps, sorry to bother if you dont care / it's to hard to make this compatible.
