### ISSUE TITLE
[1.12.2][1.0.10-99] Log spam about exception, no crash

### ISSUE THREAD

**Issue by zabi94** [DimensionalDevelopment/VanillaFix#169]
I set a PO3 Server up, the log spits out a bunch of exceptions, the server doesn't crash though, everything seems to work fine
[latest.log](https://github.com/DimensionalDevelopment/VanillaFix/files/2817208/latest.log)
[relevant snippet from log](https://pastebin.com/59c2fJsu)
[mod list](https://pastebin.com/yYWvbPRS)
I basically took PO3, removed all client side mods and grue, and added Extra Alchemy, NoMoreGlowingPots, RandomPatches

**Comment by TheRealDadbeard** [comment]
Having the same issue with this error and additionally that: 
[23:33:45] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityFancySign.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityFancySign.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
	at jds.bibliocraft.tileentities.TileEntityFancySign.getStackInSlot(TileEntityFancySign.java) ~[TileEntityFancySign.class:?]
	at com.rwtema.extrautils2.crafting.Radar$PacketPing.lambda$doStuffServer$1(Radar.java:185) ~[Radar$PacketPing.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more

No crash though!
