### ISSUE TITLE
Server Pinger Issue

### ISSUE THREAD

**Issue by RedGreenBlue09** [DimensionalDevelopment/VanillaFix#224]
Server Pinger is not working started from 1.1.
Game crashes after a while in the server list.
Small Log:

> [09:46:20] [Server Pinger #0/FATAL] [mixin]: Mixin apply failed mixins.vanillafix.bugs.json:client.MixinServerPinger$1 -> net.minecraft.client.network.ServerPinger$1: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$handleHandlePong$zbl000 could not find any targets matching 'handlePong' in the target class net.minecraft.client.network.ServerPinger$1. Using refmap mixins.vanillafix.refmap.json
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$handleHandlePong$zbl000 could not find any targets matching 'handlePong' in the target class net.minecraft.client.network.ServerPinger$1. Using refmap mixins.vanillafix.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1188) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:954) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[VanillaFix-1.1.1-138.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[VanillaFix-1.1.1-138.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.client.network.ServerPinger.func_147224_a(ServerPinger.java:63) ~[bsg.class:?]
	at net.minecraft.client.gui.ServerListEntryNormal.lambda$drawEntry$1(ServerListEntryNormal.java:759) ~[bni.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.vanillafix.bugs.json:client.MixinServerPinger$1] from phase [DEFAULT] in config [mixins.vanillafix.bugs.json] FAILED during APPLY
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.network.ServerPinger.func_147224_a(ServerPinger.java:63)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.gui.ServerListEntryNormal.lambda$drawEntry$1(ServerListEntryNormal.java:759)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Thread.run(Unknown Source)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$handleHandlePong$zbl000 could not find any targets matching 'handlePong' in the target class net.minecraft.client.network.ServerPinger$1. Using refmap mixins.vanillafix.refmap.json
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1188)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:954)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[09:46:20] [Server Pinger #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 14 more

Everything is working in build 99 (Official Forge build)

**Comment by ZombieHDGaming** [comment]
Don't use 1.1.1, it's a dev build and far from finished. Please stick with CurseForge releases.
