### ISSUE TITLE
JEID update breaks this

### ISSUE THREAD

**Issue by festro** [DimensionalDevelopment/VanillaFix#235]
JEID recently updated to Mixins 0.8 which causes this mod to crash on start as VanillaFix seems to be incompatible. Heres the crash report
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[arcanearchives-0.2.0.15.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:56) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 2 more
Caused by: java.lang.AbstractMethodError: org.dimdev.vanillafix.ModCompatibilityMixinPlugin.preApply(Ljava/lang/String;Lorg/spongepowered/asm/lib/tree/ClassNode;Ljava/lang/String;Lorg/spongepowered/asm/mixin/extensibility/IMixinInfo;)V
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1212) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1126) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:274) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[arcanearchives-0.2.0.15.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[arcanearchives-0.2.0.15.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:56) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 2 more

**Comment by BoogieMonster1O1** [comment]
Update Vanillafix. The latest version uses the same mixin version as jeid's
