### ISSUE TITLE
1.12.2 Incompatibility with Surge

### ISSUE THREAD

**Issue by thedarkcolour** [DimensionalDevelopment/VanillaFix#243]
When VanillaFix is loaded with surge (no other mods), I get a java.util.ServiceConfigurationError.
This started happening on VanillaFix version 1.0.10-150, and adding "a" to the start of the filename seems to fix this issue. "VanillaFix-1.0.10-150.jar" breaks with Surge, "aVanillaFix-1.0.10-150.jar" works.
```
[21:40:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:40:59] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:40:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:40:59] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[21:40:59] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_221, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_221
[21:40:59] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[21:40:59] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[21:40:59] [main/INFO] [FML]: Searching C:\Users\~\AppData\Roaming\GDLauncher\instances\packs\BruhPack\mods for mods
[21:40:59] [main/INFO] [FML]: Searching C:\Users\~\AppData\Roaming\GDLauncher\instances\packs\BruhPack\mods\1.12.2 for mods
[21:40:59] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.77.jar
[21:40:59] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
[21:40:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:40:59] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.fail(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.access$100(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$1.next(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.checkCerts(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.preDefineClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[21:40:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 19 more
 ```

**Comment by PulzHF** [comment]
You've saved me a lot of time troubleshooting my own issue- can reproduce this error.

**Comment by V-Boy** [comment]
Did you guys get the newest version of Surge? This is a mixin issue

**Comment by PulzHF** [comment]
> Did you guys get the newest version of Surge? This is a mixin issue
Yes, 2.0.79 crashes.

**Comment by SylisMC** [comment]
I have this same issue. looking forward to a patch :)

**Comment by ZombieHDGaming** [comment]
> I have this same issue. looking forward to a patch :)

There is no patch......it's not an incompatibility or anything Mixins needed to be updated. If you're using the latest of both mods, they work fine.

**Comment by Pulz-TCP** [comment]
> > I have this same issue. looking forward to a patch :)
> 
> There is no patch......it's not an incompatibility or anything Mixins needed to be updated. If you're using the latest of both mods, they work fine.

They probably thought this was still an issue- because it has been open _two months_ after the fix.

@SylisMC 
This fix is implemented into Surge .79, which is marked as an Alpha build- and therefore doesn't appear as the most recent mod file for those who don't scroll down the version list.

So keep that in mind when hunting future mod versions :)
