### ISSUE TITLE
[1.12.2][sponge] Player Timeouts

### ISSUE THREAD

**Issue by Invidious** [DimensionalDevelopment/VanillaFix#256]
vanillafix-1-0-10-99

Times out players randomly.

`[12:46:47] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.2.0]
	at net.minecraft.server.MinecraftServer.redirect$zje000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]`

https://gist.github.com/Invidious/3355230272b123d392ed9f40ac541383

**Comment by ZombieHDGaming** [comment]
1. First of all, neither your paste there or the Gist link to the log reveals anything besides you needing to update your VanillaFix version, and 2. Given the amount of mods installed, on top of SpongeForge as well, it is highly unlikely we have anything to do with this and more than likely either the client connection or server connection is being bottlenecked from the amount of data and packets needing to be sent and isn't able to keep up, leading to.....well, exactly what you said.

**Comment by Invidious** [comment]
@ZombieHDGaming Did you not click to expand the whole text file and scroll to the bottom?

**Comment by ZombieHDGaming** [comment]
Okay, after Gist failing to be smart and our Paste server picking the best time to be taken offline (fuck), I still stand by what I said after viewing the full log. You're connecting with 133 mods, which is a lot in terms of 1.12 standards, and, as stated, can cause a network bottleneck when trying to process all the data that is being sent. EnderStorage from CodeChicken might need a fix since there seems to be some issues happening there, but besides that, there's nothing I can do.

Hell, the log even said `Tick #34729 lasted 167621.39 ms`.........that's roughly over 2 minutes and 47 seconds for just that login tick, so this is more than likely just a minor bottleneck that can happen, but it is more than certainly not a VanillaFix issue here.
