### ISSUE TITLE
Failed to get MCP data!

### ISSUE THREAD

**Issue by jagprog5** [DimensionalDevelopment/VanillaFix#362]
For [this](https://github.com/jagprog5/modpack-client) mod pack on a forge server, vanilla fix gives a trace to [this line](https://github.com/DimensionalDevelopment/VanillaFix/blob/99cb47cc05b4790e8ef02bbcac932b21dafa107f/src/main/java/org/dimdev/vanillafix/crashes/StacktraceDeobfuscator.java#L31). Any ideas? Also, what is the host "export.mcpbot.bspk.rs"?

<details>
  <summary>Stack trace</summary>

[03:35:59] [main/INFO]: Downloading MCP method mappings to: methods-stable_39.csv
[03:35:59] [main/ERROR]: Failed to get MCP data!
java.lang.RuntimeException: java.net.UnknownHostException: export.mcpbot.bspk.rs
	at org.dimdev.vanillafix.crashes.StacktraceDeobfuscator.init(StacktraceDeobfuscator.java:52) ~[StacktraceDeobfuscator.class:?]
	at org.dimdev.vanillafix.VanillaFixLoadingPlugin.initStacktraceDeobfuscator(VanillaFixLoadingPlugin.java:60) [VanillaFix-1.0.10-150.jar:?]
	at org.dimdev.vanillafix.VanillaFixLoadingPlugin.<clinit>(VanillaFixLoadingPlugin.java:43) [VanillaFix-1.0.10-150.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_312]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) [forge-1.12.2-14.23.5.2860.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.injectCorePlugin(MixinPlatformAgentFMLLegacy.java:244) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.initFMLCoreMod(MixinPlatformAgentFMLLegacy.java:171) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.accept(MixinPlatformAgentFMLLegacy.java:157) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:74) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:143) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:135) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:220) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:107) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:107) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:154) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46) [DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_312]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_312]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_312]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2860.jar:?]
Caused by: java.net.UnknownHostException: export.mcpbot.bspk.rs
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_312]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_312]
	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_312]
	at java.net.Socket.connect(Socket.java:556) ~[?:1.8.0_312]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_312]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_312]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_312]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_312]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_312]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1223) ~[?:1.8.0_312]
	/home/john/modpack-server/data/logsat sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1046) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1044) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1043) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[?:1.8.0_312]
	at org.dimdev.vanillafix.crashes.StacktraceDeobfuscator.init(StacktraceDeobfuscator.java:31) ~[StacktraceDeobfuscator.class:?]
	... 33 more
[03:35:59] [main/INFO]: Done initializing StacktraceDeobfuscator
[03:35:59] [main/INFO]: Initializing Bug Fix Mixins
[03:35:59] [main/INFO]: Initializing Crash Fix Mixins
[03:35:59] [main/INFO]: Initializing Profiler Improvement Mixins
[03:35:59] [main/INFO]: Initializing Texture Fix Mixins
[03:35:59] [main/INFO]: Initializing Mod Support Mixins
...

</details>

**Comment by jagprog5** [comment]
I ended up [manually adding the config file](https://github.com/jagprog5/modpack-client/commit/56d7ee7009fb66a0fd3dba7241b9981dc4d493dd). But this issue should remain open until the download link is update.

**Comment by san-antonio0978** [comment]
I get the exact same issue, could you explain me in detail how to fix this (even without Curse Forge launcher and Curse Forge modpack format) ?

I don't get how to force VanillaFix to use the right "methods-stable_39.csv" file,  as the (down) host is hardcoded.

**Comment by jagprog5** [comment]
Yes the url is hard-coded but it checks if it's already downloaded first and uses that before reaching to the down website.

The curseforge "overrides" folder populates the same paths in the Minecraft folder. So the "config" folder in the pack is equivalent to the "config" folder in the Minecraft directory. Using that, place the same file I put in my pack into the same place and same name as your Minecraft instance.
